#!/usr/bin/env node
/**
 * Build the subtitle/title layer for the reel.
 *
 * All on-screen text lives here, not in the artwork: titles, column labels and the
 * word-by-word caption. libass renders them as real vector type, which is why the
 * reference reel's garbled "multiple incomeest opportunities" frame cannot happen to us.
 *
 *   node make-ass.mjs scenes.json [words.json] > captions.ass
 *
 * words.json is optional. Supply it once you have real voiceover timings:
 *   [{ "word": "If", "start": 0.31, "end": 0.44 }, ...]
 * Without it, each scene's VO line is spread evenly across the scene so you can cut a
 * timing check before the voiceover exists. Even spacing always looks slightly off the
 * beat — that is expected, and it is the thing real timings fix.
 */
import fs from 'node:fs';

const [, , scenesPath, wordsPath] = process.argv;
if (!scenesPath) {
  console.error('usage: node make-ass.mjs scenes.json [words.json] > captions.ass');
  process.exit(1);
}

const doc = JSON.parse(fs.readFileSync(scenesPath, 'utf8'));
const words = wordsPath ? JSON.parse(fs.readFileSync(wordsPath, 'utf8')) : null;
const { width: W, height: H } = doc.master;

/** ASS colours are &HAABBGGRR — byte-reversed from hex, and easy to get wrong by hand. */
function assColour(hex, alpha = '00') {
  const h = hex.replace('#', '');
  const r = h.slice(0, 2), g = h.slice(2, 4), b = h.slice(4, 6);
  return `&H${alpha}${b}${g}${r}`.toUpperCase();
}

/** ASS timestamps are H:MM:SS.cc — centiseconds, single-digit hour, no leading zero. */
function ts(seconds) {
  const s = Math.max(0, seconds);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = Math.floor(s % 60);
  const cs = Math.round((s - Math.floor(s)) * 100);
  const cc = cs === 100 ? 99 : cs;
  return `${h}:${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')}.${String(cc).padStart(2, '0')}`;
}

const C = doc.brand;
const FONT_DISPLAY = process.env.REEL_FONT_DISPLAY || 'DejaVu Sans';
const FONT_CAPTION = process.env.REEL_FONT_CAPTION || 'DejaVu Sans';

// Layout anchors as a fraction of frame height, mirroring the storyboard's template.
const Y_TITLE = Math.round(H * 0.085);
const Y_LABEL = Math.round(H * 0.20);
const Y_CAPTION = Math.round(H * 0.82);
const X_LEFT = Math.round(W * 0.25);
const X_RIGHT = Math.round(W * 0.75);

const header = `[Script Info]
; Generated by make-ass.mjs — do not hand-edit, regenerate instead.
ScriptType: v4.00+
PlayResX: ${W}
PlayResY: ${H}
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Title,${FONT_DISPLAY},96,${assColour(C.ink)},${assColour(C.ink)},${assColour(C.ground)},&H00000000,-1,0,0,0,100,100,-1,0,1,0,0,8,60,60,60,1
Style: LabelBad,${FONT_DISPLAY},46,${assColour(C.alert)},${assColour(C.alert)},${assColour(C.ground)},&H00000000,-1,0,0,0,100,100,0,0,1,0,0,8,20,20,20,1
Style: LabelGood,${FONT_DISPLAY},46,${assColour(C.green)},${assColour(C.green)},${assColour(C.ground)},&H00000000,-1,0,0,0,100,100,0,0,1,0,0,8,20,20,20,1
Style: Caption,${FONT_CAPTION},64,${assColour(C.captionFill)},${assColour(C.captionFill)},${assColour(C.navy)},&H00000000,-1,-1,0,0,100,100,1,0,1,6,0,2,40,40,40,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text`;

const lines = [header];
const ev = (layer, start, end, style, x, y, text) =>
  lines.push(`Dialogue: ${layer},${ts(start)},${ts(end)},${style},,0,0,0,,{\\an5\\pos(${x},${y})}${text}`);

for (const s of doc.scenes) {
  // Titles and labels hold for the whole scene — they are part of the frame, not an effect.
  ev(1, s.start, s.end, 'Title', Math.round(W / 2), Y_TITLE, s.title);
  ev(1, s.start, s.end, 'LabelBad', X_LEFT, Y_LABEL, s.labelLeft);
  ev(1, s.start, s.end, 'LabelGood', X_RIGHT, Y_LABEL, s.labelRight);

  // One word at a time, centred in the reserved bottom band.
  const scoped = words
    ? words.filter((w) => w.start >= s.start - 0.01 && w.start < s.end)
    : null;

  if (scoped && scoped.length) {
    for (const w of scoped) {
      ev(2, w.start, Math.min(w.end, s.end), 'Caption', Math.round(W / 2), Y_CAPTION,
        w.word.toUpperCase());
    }
  } else {
    const tokens = s.vo.split(/\s+/).filter(Boolean);
    const step = (s.end - s.start) / tokens.length;
    tokens.forEach((tok, i) => {
      ev(2, s.start + i * step, s.start + (i + 1) * step, 'Caption',
        Math.round(W / 2), Y_CAPTION, tok.toUpperCase());
    });
  }
}

process.stdout.write(lines.join('\n') + '\n');
